FROM mysql

# ENV MYSQL_RANDOM_ROOT_PASSWORD yes
# ENV MYSQL_DATABASE busirate
# ENV MYSQL_USER busi-user
# ENV MYSQL_PASSWORD asdfqwer1234

COPY /initdb.sh .
# CMD ./initdb.sh
# RUN ./initdb.sh

EXPOSE ${PORT}

# ENTRYPOINT ./initdb.sh